Update MIP46.md
MakerDAO/MIPs pull request #526
Opened 2022-04-18 12:19 UTC by tylerrihn

@blimpa howdy :) I made some edits for grammar/formatting for this MIP46; nothing big! Give a look and merge to master if you think everything is looking alright.

MIP46 Tracked Changes: Parameter Proposal Groups
-	Updated Dating Structure to reflect ISO standard YYYY, MM,DD

Sentence Summary
-	2nd line, capitalize “Contributors” and Domain Teams
-	Change Domain Teams to Core Units??
-	Capitalize Parameter Change Proposals
Paragraph Summary
-	Capitalize Contributors and Domain Teams
-	Capitalize Parameter Change Proposals
-	Capitalize Prameter Adjustment Proposals
Mip46c3
-	Capitalize Parameter Proposals
Motivation
-	Remove comma after “complexity”, first sentence.

Specification/Proposal Details
-	Capitalize “Parameter Proposal Group”, first paragraph

Mip46c2 Parameter Proposal Requirements:
-	Capitalize Parameter Proposal, first sentence
Mip46c3: Parameter Proposal Process:
-	Capitalize Weekly Governance Cycle
-	Grammar Change 3rd Sentence, replace “, and” with a period.

2022-04-18 18:37 UTC, blimpa requested changes

2022-04-18 18:37 UTC, blimpa commented on MIP46/MIP46.md
> +Proposed Parameter Changes will be bundled into a single on-chain poll for inclusion in the weekly cycle. If the outcome is favorable, it will proceed to that week's executive vote absent unforeseen
Capitalize "weekly cycle" here

2022-04-18 18:48 UTC, tylerrihn commented on MIP46/MIP46.md
> +Proposed Parameter Changes will be bundled into a single on-chain poll for inclusion in the weekly cycle. If the outcome is favorable, it will proceed to that week's executive vote absent unforeseen
yessir

2022-04-18 19:00 UTC, blimpa commented
LGTM :)

2022-04-20 16:57 UTC, blimpa approved these changes
Thank you!

2022-04-20 16:57 UTC, merged