Update mip38.md
MakerDAO/MIPs pull request #863
Opened 2023-03-28 22:11 UTC by blimpa

- Retro as Facilitator for CES-001
- BA Labs as Facilitator for RISK-001

2023-03-30 04:05 UTC, Gala-G commented
Are we including the budget changes? Or should we mark all CUs as offboarded? Should also update SF's budget.
@blimpa

2023-03-30 10:23 UTC, patrick-j-govalpha requested changes

2023-03-30 10:23 UTC, patrick-j-govalpha commented on MIP38/mip38.md
> +- BA Labs, LLC - [MIP41c4-SP41](https://github.com/makerdao/mips/blob/master/MIP41/MIP41c4-Subproposals/MIP41c4-SP41.md)
MIPs Portal vs. github for links? I'd tend to thing MIPs Portal tbh

2023-03-30 10:23 UTC, patrick-j-govalpha commented on MIP38/mip38.md
> +- @Retro - [MIP41c4-SP40](https://github.com/makerdao/mips/blob/master/MIP41/MIP41c4-Subproposals/MIP41c4-SP40.md).
MIPs Portal vs. github for links? I'd tend to thing MIPs Portal tbh

2023-03-30 10:23 UTC, patrick-j-govalpha commented on MIP38/mip38.md
> +- BA Labs, LLC - [MIP41c4-SP41](https://github.com/makerdao/mips/blob/master/MIP41/MIP41c4-Subproposals/MIP41c4-SP41.md)
```suggestion
- BA Labs, LLC (represented by @rema and @monet-supply) - [MIP41c4-SP41](https://github.com/makerdao/mips/blob/master/MIP41/MIP41c4-Subproposals/MIP41c4-SP41.md)
```

2023-04-18 14:26 UTC, patrick-j-govalpha commented
@blimpa is there an update on this PR?

2023-04-18 20:25 UTC, blimpa commented
> @blimpa is there an update on this PR?

Sorry. Totally missed this

2023-04-19 11:23 UTC, patrick-j-govalpha approved these changes

2023-04-19 11:23 UTC, merged