Stability Scope Format Fix
MakerDAO/MIPs pull request #930
Opened 2023-06-29 11:28 UTC by Hipogeo

@blimpa @Gala-G

2023-06-30 22:36 UTC, blimpa requested changes
Corrections are not exhaustive. Generally, some of these are titles and should be kept next to the article code (x.x.x...); also, they should be capitalized

2023-06-30 22:36 UTC, blimpa commented on MIP104/MIP104.md
> +#### 7.1.1
```suggestion
#### 7.1.1: ALM Capitalization Requirements
```

2023-06-30 22:36 UTC, blimpa commented on MIP104/MIP104.md
> +##### 7.1.1.1
```suggestion
##### 7.1.1.1: ALM Tier 1 Collateral
```

2023-06-30 22:36 UTC, blimpa commented on MIP104/MIP104.md
> +##### 7.1.1.2
```suggestion
##### 7.1.1.2: ALM Tier 2 Collateral
```

2023-06-30 22:36 UTC, blimpa commented on MIP104/MIP104.md
> +##### 7.1.1.3
```suggestion
##### 7.1.1.3: ALM Tier 3 Collateral
```

2023-06-30 22:36 UTC, blimpa commented on MIP104/MIP104.md
> +#### 7.1.2
```suggestion
#### 7.1.2: Risk Capitalization Requirements
```

2023-07-07 15:17 UTC, blimpa commented
LGTM :)

2023-07-07 15:18 UTC, blimpa commented
Check the 1 articles: remove colons and add a new line, as we discussed

2023-07-11 13:34 UTC, patrick-j-govalpha commented
> Check the 1 articles: remove colons and add a new line, as we discussed

@Hipogeo please address these issue raised by @blimpa so we can merge

2023-07-14 10:58 UTC, patrick-j-govalpha approved these changes

2023-07-14 10:58 UTC, merged