Scopes: Format Fixes
MakerDAO/MIPs pull request #931
Opened 2023-06-29 12:22 UTC by Gala-G

MIPs 106, 107, 108, 113

@patrick-j-govalpha 
@blimpa

2023-06-30 15:16 UTC, patrick-j-govalpha requested changes

2023-06-30 15:16 UTC, patrick-j-govalpha commented on MIP106/MIP106.md
> +##### 1.1.2.1
Colons `:` after every number please

```suggestion
##### 1.1.2.1:
```

2023-07-04 20:54 UTC, Gala-G commented
@patrick-j-govalpha 
@blimpa

2023-07-07 15:10 UTC, blimpa commented
LGTM :)

2023-07-07 16:42 UTC, patrick-j-govalpha approved these changes
LGTM

2023-07-07 16:42 UTC, merged